### ISSUE TITLE
The following github version of gems take long time to install. Please use the rubygems version.

### ISSUE THREAD

**Issue by yzhanginwa** [rivsc/Beautiful-Scaffold#15]
gem('less-rails', :github => "CQQL/less-rails", :branch => 'less-2.5')
    gem('ransack', :github => 'activerecord-hackery/ransack', :branch => 'rails-4.2')
    gem('polyamorous', :github => 'activerecord-hackery/polyamorous')
    gem('twitter-bootstrap-rails', :github => 'seyhunak/twitter-bootstrap-rails', :branch => 'bootstrap3')

**Comment by rivsc** [comment]
Fixed.
