### ISSUE TITLE
Responsive Theme Navbar Overlaps Content When Resizing Below ~979px

### ISSUE THREAD

**Issue by jonmchan** [rivsc/Beautiful-Scaffold#18]
When you resize the view to below 979px, the responsive theme takes into effect and minimizes the navbar however the navbar blocks the content of the screen such that the content is behind the navbar. 

The fix is simply fixing the padding-top for mobile screen size in ```beautiful-scaffold.css.scss```:

```
@media (max-width: 979px) {
  .fixed + div {
    margin-left: 0;
    padding:10px;
  }
  body {
    padding-top:35px;
  }
}
```

**Comment by rivsc** [comment]
Thanks !
