### ISSUE TITLE
beautiful_devisecancan errors

### ISSUE THREAD

**Issue by boss94** [rivsc/Beautiful-Scaffold#3]
First, thanks a lot for this amazing tool, it helped a lot to get into rails quickly. 

But I just have one limitation worth mentioning with the devisecancan generator:
- we need to have an existing user model set to do the generation otherwise, an exception is thrown at line 35 of the generator because the migration file generated by devise will be called '__create_devise__' instead of '__add_devise_to_'.

**Comment by rivsc** [comment]
2013... ;( sorry. I replaced Devise by Sorcery.
